<a href="https://colab.research.google.com/github/Pheonix1795/MDS_LAB/blob/main/MDS_WEEK5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Create Pandas Series and Data Frame from various inputs

In [10]:
import pandas as pd

# Creating a Series from a simple list
my_data_list = [5, 10, 15, 20]
my_series = pd.Series(my_data_list)
print("Simple Series:")
print(my_series)

# Creating a DataFrame from a dictionary
my_data_dict = {
    'Fruit': ['Apple', 'Banana', 'Cherry'],
    'Price': [1.2, 0.5, 2.5]
}
my_df = pd.DataFrame(my_data_dict)
print("\nSimple DataFrame:")
display(my_df)

Simple Series:
0     5
1    10
2    15
3    20
dtype: int64

Simple DataFrame:

    Fruit  Price
0   Apple    1.2
1  Banana    0.5
2  Cherry    2.5

# 2. Import CSV file to Pandas Data Frame

In [11]:
# Loading the selected hospital data file
file_path = '/content/Hospital_Management_System_50_with_Nulls_Combined.csv'
hospital_df = pd.read_csv(file_path)
print("File loaded successfully!")

File loaded successfully!

## (a) Visualize the first and last 10 records

In [12]:
print("First 10 records:")
display(hospital_df.head(10))

print("\nLast 10 records:")
display(hospital_df.tail(10))

First 10 records:

,Table_Name,Patient_ID,Patient_Name,Age,Gender,Phone,Disease,Doctor_ID,Doctor_Name,Specialization,Appointment_ID,Appointment_Date,Status,Treatment_ID,Treatment,Cost,Bill_ID,Amount,Payment_Status
0,Patients,1.0,Aarav Sharma,24.0,Male,9.870000e+09,Fever,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Patients,2.0,Priya Reddy,31.0,Female,9.870000e+09,Diabetes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Patients,3.0,Rahul Kumar,45.0,Male,9.870000e+09,Hypertension,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Patients,4.0,Sneha Patel,28.0,Female,9.870000e+09,Migraine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Patients,5.0,Arjun Rao,52.0,Male,9.870000e+09,Asthma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Patients,6.0,Ananya Singh,36.0,Female,9.870000e+09,Arthritis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Patients,7.0,Vikram Das,41.0,Male,9.870000e+09,Cold,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Patients,8.0,Kavya Nair,23.0,Female,NaN,Gastritis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Patients,9.0,Rohan Gupta,57.0,Male,9.870000e+09,Heart Disease,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Patients,10.0,Meera Joshi,34.0,Female,9.870000e+09,Anemia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Last 10 records:

,Table_Name,Patient_ID,Patient_Name,Age,Gender,Phone,Disease,Doctor_ID,Doctor_Name,Specialization,Appointment_ID,Appointment_Date,Status,Treatment_ID,Treatment,Cost,Bill_ID,Amount,Payment_Status
200,Billing,41.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,NaN,NaN,41.0,500.0,Paid
201,Billing,42.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.0,NaN,NaN,42.0,800.0,Paid
202,Billing,43.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.0,NaN,NaN,43.0,1200.0,Pending
203,Billing,44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,NaN,44.0,1500.0,Paid
204,Billing,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,NaN,NaN,45.0,700.0,Pending
205,Billing,46.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,NaN,NaN,46.0,1000.0,Paid
206,Billing,47.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.0,NaN,NaN,47.0,600.0,Paid
207,Billing,48.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,NaN,NaN,48.0,1800.0,Pending
208,Billing,49.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.0,NaN,NaN,49.0,3500.0,Paid
209,Billing,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,NaN,NaN,50.0,900.0,Pending

## (b) Get the shape, index and column details

In [13]:
print("Rows and Columns count:", hospital_df.shape)
print("\nIndex of the data:", hospital_df.index)
print("\nColumn names:", hospital_df.columns.tolist())

Rows and Columns count: (210, 19)

Index of the data: RangeIndex(start=0, stop=210, step=1)

Column names: ['Table_Name', 'Patient_ID', 'Patient_Name', 'Age', 'Gender', 'Phone', 'Disease', 'Doctor_ID', 'Doctor_Name', 'Specialization', 'Appointment_ID', 'Appointment_Date', 'Status', 'Treatment_ID', 'Treatment', 'Cost', 'Bill_ID', 'Amount', 'Payment_Status']

## (c) Select/Delete records and columns based on conditions

In [14]:
# Selection: Rows where 'Age' is greater than 30 (adjusting column name based on likely CSV content)
# Note: We check if 'Age' exists first
if 'Age' in hospital_df.columns:
    older_patients = hospital_df[hospital_df['Age'] > 30]
    print("Rows where Age > 30:")
    display(older_patients.head())

# Deletion: Drop the 'Phone' column if it exists
if 'Phone' in hospital_df.columns:
    df_no_phone = hospital_df.drop(columns=['Phone'])
    print("\nData after dropping 'Phone' column:")
    display(df_no_phone.head())

Rows where Age > 30:

,Table_Name,Patient_ID,Patient_Name,Age,Gender,Phone,Disease,Doctor_ID,Doctor_Name,Specialization,Appointment_ID,Appointment_Date,Status,Treatment_ID,Treatment,Cost,Bill_ID,Amount,Payment_Status
1,Patients,2.0,Priya Reddy,31.0,Female,9.870000e+09,Diabetes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Patients,3.0,Rahul Kumar,45.0,Male,9.870000e+09,Hypertension,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Patients,5.0,Arjun Rao,52.0,Male,9.870000e+09,Asthma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Patients,6.0,Ananya Singh,36.0,Female,9.870000e+09,Arthritis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Patients,7.0,Vikram Das,41.0,Male,9.870000e+09,Cold,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Data after dropping 'Phone' column:

,Table_Name,Patient_ID,Patient_Name,Age,Gender,Disease,Doctor_ID,Doctor_Name,Specialization,Appointment_ID,Appointment_Date,Status,Treatment_ID,Treatment,Cost,Bill_ID,Amount,Payment_Status
0,Patients,1.0,Aarav Sharma,24.0,Male,Fever,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Patients,2.0,Priya Reddy,31.0,Female,Diabetes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Patients,3.0,Rahul Kumar,45.0,Male,Hypertension,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Patients,4.0,Sneha Patel,28.0,Female,Migraine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Patients,5.0,Arjun Rao,52.0,Male,Asthma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## (d) Perform ranking and sorting operations

In [15]:
# Sorting by the first column in the DataFrame
first_col = hospital_df.columns[0]
df_sorted = hospital_df.sort_values(by=first_col, ascending=True)
print(f"Sorted by {first_col}:")
display(df_sorted.head())

# Ranking values in the second column
second_col = hospital_df.columns[1]
hospital_df['Rank_Value'] = hospital_df[second_col].rank()
print(f"\nData with Rank column based on {second_col}:")
display(hospital_df.head())

Sorted by Table_Name:

,Table_Name,Patient_ID,Patient_Name,Age,Gender,Phone,Disease,Doctor_ID,Doctor_Name,Specialization,Appointment_ID,Appointment_Date,Status,Treatment_ID,Treatment,Cost,Bill_ID,Amount,Payment_Status
104,Appointments,45.0,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,45.0,2026-04-03,Completed,NaN,NaN,NaN,NaN,NaN,NaN
71,Appointments,12.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,12.0,2026-01-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,Appointments,11.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,11.0,2026-01-25,Completed,NaN,NaN,NaN,NaN,NaN,NaN
69,Appointments,10.0,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,10.0,2026-01-23,Completed,NaN,NaN,NaN,NaN,NaN,NaN
68,Appointments,9.0,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,9.0,2026-01-21,Cancelled,NaN,NaN,NaN,NaN,NaN,NaN

Data with Rank column based on Patient_ID:

,Table_Name,Patient_ID,Patient_Name,Age,Gender,Phone,Disease,Doctor_ID,Doctor_Name,Specialization,Appointment_ID,Appointment_Date,Status,Treatment_ID,Treatment,Cost,Bill_ID,Amount,Payment_Status,Rank_Value
0,Patients,1.0,Aarav Sharma,24.0,Male,9.870000e+09,Fever,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.5
1,Patients,2.0,Priya Reddy,31.0,Female,9.870000e+09,Diabetes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.5
2,Patients,3.0,Rahul Kumar,45.0,Male,9.870000e+09,Hypertension,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.5
3,Patients,4.0,Sneha Patel,28.0,Female,9.870000e+09,Migraine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.5
4,Patients,5.0,Arjun Rao,52.0,Male,9.870000e+09,Asthma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.5

## (e) Statistical operations on the given columns

In [16]:
print("Statistical summary for numeric data:")
display(hospital_df.describe())

Statistical summary for numeric data:

,Patient_ID,Age,Phone,Doctor_ID,Appointment_ID,Treatment_ID,Cost,Bill_ID,Amount,Rank_Value
count,200.000000,49.000000,5.800000e+01,110.000000,50.00000,100.00000,49.000000,50.00000,49.000000,200.000000
mean,25.500000,40.673469,9.697759e+09,5.500000,25.50000,25.50000,1263.265306,25.50000,1261.224490,100.500000
std,14.467083,11.868003,4.054066e+08,2.885427,14.57738,14.50357,855.056986,14.57738,856.547412,57.868331
min,1.000000,21.000000,8.760000e+09,1.000000,1.00000,1.00000,500.000000,1.00000,500.000000,2.500000
25%,13.000000,31.000000,9.870000e+09,3.000000,13.25000,13.00000,700.000000,13.25000,700.000000,50.500000
50%,25.500000,40.000000,9.870000e+09,5.500000,25.50000,25.50000,1000.000000,25.50000,1000.000000,100.500000
75%,38.000000,50.000000,9.870000e+09,8.000000,37.75000,38.00000,1500.000000,37.75000,1500.000000,150.500000
max,50.000000,62.000000,9.870000e+09,10.000000,50.00000,50.00000,3500.000000,50.00000,3500.000000,198.500000

## (f) Count and uniqueness of categorical values

In [17]:
# Finding a categorical column (text-based)
cat_col = hospital_df.select_dtypes(include=['object']).columns[0]
print(f"Column analyzed: {cat_col}")
print(f"Number of unique items: {hospital_df[cat_col].nunique()}")
print("\nCounts for each item:")
print(hospital_df[cat_col].value_counts())

Column analyzed: Table_Name
Number of unique items: 5

Counts for each item:
Table_Name
Patients        50
Appointments    50
Treatments      50
Billing         50
Doctors         10
Name: count, dtype: int64

## (g) Rename single/multiple columns

In [18]:
# Renaming the first column to 'ID_Number' and second to 'Main_Entry'
renamed_df = hospital_df.rename(columns={
    hospital_df.columns[0]: 'ID_Number',
    hospital_df.columns[1]: 'Main_Entry'
})
print("Columns after renaming:")
print(renamed_df.columns.tolist()[:5])

Columns after renaming:
['ID_Number', 'Main_Entry', 'Patient_Name', 'Age', 'Gender']