<a href="https://colab.research.google.com/github/Pheonix1795/MDS_LAB/blob/main/MDS_WEEK6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Load the CSV file into a Pandas DataFrame
file_path = '/content/Hospital_Management_System_50_with_Nulls_Combined.csv'
df = pd.read_csv(file_path)

print(f"Successfully loaded data from: {file_path}")
print("First 5 rows of the DataFrame:")
display(df.head())

Successfully loaded data from: /content/Hospital_Management_System_50_with_Nulls_Combined.csv
First 5 rows of the DataFrame:

,Table_Name,Patient_ID,Patient_Name,Age,Gender,Phone,Disease,Doctor_ID,Doctor_Name,Specialization,Appointment_ID,Appointment_Date,Status,Treatment_ID,Treatment,Cost,Bill_ID,Amount,Payment_Status
0,Patients,1.0,Aarav Sharma,24.0,Male,9.870000e+09,Fever,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Patients,2.0,Priya Reddy,31.0,Female,9.870000e+09,Diabetes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Patients,3.0,Rahul Kumar,45.0,Male,9.870000e+09,Hypertension,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Patients,4.0,Sneha Patel,28.0,Female,9.870000e+09,Migraine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Patients,5.0,Arjun Rao,52.0,Male,9.870000e+09,Asthma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## (a) Handle missing data by detecting and dropping/filling missing values.

First, let's identify the missing values in the dataset.

In [ ]:
# Identify null values
null_counts = df.isnull().sum()
print("Number of null values per column:")
display(null_counts[null_counts > 0])

# Identify non-null values
non_null_counts = df.notnull().sum()
print("\nNumber of non-null values per column:")
display(non_null_counts)

Number of null values per column:

Patient_ID           10
Patient_Name        160
Age                 161
Gender              160
Phone               152
Disease             161
Doctor_ID           100
Doctor_Name         200
Specialization      201
Appointment_ID      160
Appointment_Date    161
Status              161
Treatment_ID        110
Treatment           161
Cost                161
Bill_ID             160
Amount              161
Payment_Status      161
dtype: int64

Number of non-null values per column:

Table_Name          210
Patient_ID          200
Patient_Name         50
Age                  49
Gender               50
Phone                58
Disease              49
Doctor_ID           110
Doctor_Name          10
Specialization        9
Appointment_ID       50
Appointment_Date     49
Status               49
Treatment_ID        100
Treatment            49
Cost                 49
Bill_ID              50
Amount               49
Payment_Status       49
dtype: int64

### Handling Missing Values

Let's apply strategies to handle the identified missing values.

In [ ]:
# Calculate the percentage of missing values for each column
missing_percentage = df.isnull().sum() / len(df) * 100

# Identify columns to drop (e.g., more than 70% missing)
columns_to_drop = missing_percentage[missing_percentage > 70].index
df_cleaned = df.drop(columns=columns_to_drop)
print(f"Dropped columns with more than 70% missing values: {list(columns_to_drop)}")

# Fill remaining missing numerical values with the mean
for col in df_cleaned.select_dtypes(include=['number']).columns:
    if df_cleaned[col].isnull().any():
        df_cleaned[col].fillna(df_cleaned[col].mean(), inplace=True)

# Fill remaining missing categorical values with the mode
for col in df_cleaned.select_dtypes(include=['object']).columns:
    if df_cleaned[col].isnull().any():
        df_cleaned[col].fillna(df_cleaned[col].mode()[0], inplace=True)

print("\nMissing values after handling:")
display(df_cleaned.isnull().sum()[df_cleaned.isnull().sum() > 0])
print("\nFirst 5 rows of the DataFrame after handling missing values:")
display(df_cleaned.head())

Dropped columns with more than 70% missing values: ['Patient_Name', 'Age', 'Gender', 'Phone', 'Disease', 'Doctor_Name', 'Specialization', 'Appointment_ID', 'Appointment_Date', 'Status', 'Treatment', 'Cost', 'Bill_ID', 'Amount', 'Payment_Status']

Missing values after handling:

/tmp/ipykernel_1257/101137631.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned[col].fillna(df_cleaned[col].mean(), inplace=True)

Series([], dtype: int64)

First 5 rows of the DataFrame after handling missing values:

  Table_Name  Patient_ID  Doctor_ID  Treatment_ID
0   Patients         1.0        5.5          25.5
1   Patients         2.0        5.5          25.5
2   Patients         3.0        5.5          25.5
3   Patients         4.0        5.5          25.5
4   Patients         5.0        5.5          25.5

## (b) Detect and filter outliers.

Let's detect outliers using the IQR method and then filter them out.

In [ ]:
# Detect and filter outliers using IQR method for numerical columns
Q1 = df_cleaned.select_dtypes(include=['number']).quantile(0.25)
Q3 = df_cleaned.select_dtypes(include=['number']).quantile(0.75)
IQR = Q3 - Q1

# Define bounds for outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Filter out outliers
df_filtered = df_cleaned.copy()
for col in df_cleaned.select_dtypes(include=['number']).columns:
    df_filtered = df_filtered[~((df_filtered[col] < lower_bound[col]) | (df_filtered[col] > upper_bound[col]))]

print(f"Original DataFrame shape: {df_cleaned.shape}")
print(f"DataFrame shape after outlier removal: {df_filtered.shape}")
print("\nFirst 5 rows of the DataFrame after outlier removal:")
display(df_filtered.head())

Original DataFrame shape: (210, 4)
DataFrame shape after outlier removal: (74, 4)

First 5 rows of the DataFrame after outlier removal:

  Table_Name  Patient_ID  Doctor_ID  Treatment_ID
0   Patients         1.0        5.5          25.5
1   Patients         2.0        5.5          25.5
2   Patients         3.0        5.5          25.5
3   Patients         4.0        5.5          25.5
4   Patients         5.0        5.5          25.5

## (c) Confirm all numerical missing values filled with mean

Let's verify that no numerical columns contain null values.

In [ ]:
# Section (c): Identify and show non-null counts clearly
# We will display a summary table showing how many values are present vs missing
null_summary = pd.DataFrame({
    'Total Rows': len(df_filtered),
    'Values Present': df_filtered.count(),
    'Missing Values': df_filtered.isnull().sum()
})
print("Data Completeness Summary:")
display(null_summary)

Data Completeness Summary:

              Total Rows  Values Present  Missing Values
Table_Name            74              74               0
Patient_ID            74              74               0
Doctor_ID             74              74               0
Treatment_ID          74              74               0

## (d) Check for duplicate rows in dataframe

We will now identify if there are any duplicate records.

In [ ]:
# Section (d): Check for duplicate rows
# Showing 'partial' duplicates (same Patient_ID) to provide actual data rows
# as there are no 100% identical row duplicates.

print("Checking for rows with duplicate Patient IDs to show multiple entries:")
patient_dupes = df_filtered[df_filtered.duplicated(subset=['Patient_ID'], keep=False)]

if not patient_dupes.empty:
    display(patient_dupes.sort_values(by='Patient_ID'))
else:
    print("No overlapping Patient IDs found in the filtered set.")
    display(df_filtered.head())

Checking for rows with duplicate Patient IDs to show multiple entries:

       Table_Name  Patient_ID  Doctor_ID  Treatment_ID
3        Patients         4.0        5.5          25.5
63   Appointments         4.0        4.0          25.5
64   Appointments         5.0        5.0          25.5
4        Patients         5.0        5.5          25.5
5        Patients         6.0        5.5          25.5
65   Appointments         6.0        6.0          25.5
66   Appointments         7.0        7.0          25.5
6        Patients         7.0        5.5          25.5
13       Patients        14.0        5.5          25.5
73   Appointments        14.0        4.0          25.5
74   Appointments        15.0        5.0          25.5
14       Patients        15.0        5.5          25.5
15       Patients        16.0        5.5          25.5
75   Appointments        16.0        6.0          25.5
76   Appointments        17.0        7.0          25.5
16       Patients        17.0        5.5          25.5
23       Patients        24.0        5.5          25.5
83   Appointments        24.0        4.0          25.5
84   Appointments        25.0        5.0          25.5
24       Patients        25.0        5.5          25.5
55        Doctors        25.5        6.0          25.5
56        Doctors        25.5        7.0          25.5
53        Doctors        25.5        4.0          25.5
54        Doctors        25.5        5.0          25.5
25       Patients        26.0        5.5          25.5
85   Appointments        26.0        6.0          25.5
86   Appointments        27.0        7.0          25.5
26       Patients        27.0        5.5          25.5
33       Patients        34.0        5.5          25.5
93   Appointments        34.0        4.0          25.5
94   Appointments        35.0        5.0          25.5
34       Patients        35.0        5.5          25.5
95   Appointments        36.0        6.0          25.5
35       Patients        36.0        5.5          25.5
36       Patients        37.0        5.5          25.5
96   Appointments        37.0        7.0          25.5
103  Appointments        44.0        4.0          25.5
43       Patients        44.0        5.5          25.5
44       Patients        45.0        5.5          25.5
104  Appointments        45.0        5.0          25.5
105  Appointments        46.0        6.0          25.5
45       Patients        46.0        5.5          25.5
46       Patients        47.0        5.5          25.5
106  Appointments        47.0        7.0          25.5

## (e) Display unique values

Finally, let's look at the unique values available in each column.

In [ ]:
# Display unique values for each column
for col in df_filtered.columns:
    unique_vals = df_filtered[col].unique()
    print(f"\nUnique values in '{col}' ({len(unique_vals)} unique values):")
    print(unique_vals)

Unique values in 'Table_Name' (3 unique values):
['Patients' 'Doctors' 'Appointments']

Unique values in 'Patient_ID' (51 unique values):
[ 1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
 15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
 29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
 43.  44.  45.  46.  47.  48.  49.  50.  25.5]

Unique values in 'Doctor_ID' (5 unique values):
[5.5 4.  5.  6.  7. ]

Unique values in 'Treatment_ID' (1 unique values):
[25.5]

## Processing Online Shopping Management Dataset

We will now repeat the data processing pipeline for the new dataset, including:
1. Loading and initial inspection.
2. Handling missing data.
3. Outlier detection and filtering.
4. Verification of nulls and duplicates.

In [ ]:
import zipfile
import os

# Extract the zip file
zip_path = '/content/Online_Shopping_Management_50_CSV_with_Nulls.zip'
extract_path = '/content/online_shopping_data'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

# Find the CSV file inside the extracted folder
csv_files = [f for f in os.listdir(extract_path) if f.endswith('.csv')]
shop_file_path = os.path.join(extract_path, csv_files[0])

# Load the data
df_shop = pd.read_csv(shop_file_path)
print(f"Successfully loaded: {shop_file_path}")
display(df_shop.head())

Successfully loaded: /content/online_shopping_data/Payments_50_with_nulls.csv

   Payment_ID  Order_ID  Amount    Payment_Method Payment_Status
0           1         1     799               UPI           Paid
1           2         2    2598       Credit Card           Paid
2           3         3     999        Debit Card        Pending
3           4         4    1047  Cash on Delivery           Paid
4           5         5    2998               UPI           Paid

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

### (a) Handle missing data for Shopping Dataset

In [ ]:
# Calculate missing percentage
shop_missing_pct = df_shop.isnull().sum() / len(df_shop) * 100
shop_cols_to_drop = shop_missing_pct[shop_missing_pct > 70].index
df_shop_cleaned = df_shop.drop(columns=shop_cols_to_drop)

# Fill numerical with mean
for col in df_shop_cleaned.select_dtypes(include=['number']).columns:
    if df_shop_cleaned[col].isnull().any():
        df_shop_cleaned[col] = df_shop_cleaned[col].fillna(df_shop_cleaned[col].mean())

# Fill categorical with mode
for col in df_shop_cleaned.select_dtypes(include=['object']).columns:
    if df_shop_cleaned[col].isnull().any():
        df_shop_cleaned[col] = df_shop_cleaned[col].fillna(df_shop_cleaned[col].mode()[0])

print(f"Dropped columns: {list(shop_cols_to_drop)}")
print("Missing values after cleaning:")
display(df_shop_cleaned.isnull().sum())
display(df_shop_cleaned.head())

Dropped columns: []
Missing values after cleaning:

Payment_ID        0
Order_ID          0
Amount            0
Payment_Method    0
Payment_Status    0
dtype: int64

   Payment_ID  Order_ID  Amount    Payment_Method Payment_Status
0           1         1     799               UPI           Paid
1           2         2    2598       Credit Card           Paid
2           3         3     999        Debit Card        Pending
3           4         4    1047  Cash on Delivery           Paid
4           5         5    2998               UPI           Paid

### (b) Detect and filter outliers for Shopping Dataset

In [ ]:
# IQR Method
Q1_s = df_shop_cleaned.select_dtypes(include=['number']).quantile(0.25)
Q3_s = df_shop_cleaned.select_dtypes(include=['number']).quantile(0.75)
IQR_s = Q3_s - Q1_s

df_shop_filtered = df_shop_cleaned.copy()
for col in df_shop_cleaned.select_dtypes(include=['number']).columns:
    lower = Q1_s[col] - 1.5 * IQR_s[col]
    upper = Q3_s[col] + 1.5 * IQR_s[col]
    df_shop_filtered = df_shop_filtered[~((df_shop_filtered[col] < lower) | (df_shop_filtered[col] > upper))]

print(f"Shape before: {df_shop_cleaned.shape}, Shape after: {df_shop_filtered.shape}")

Shape before: (50, 5), Shape after: (50, 5)

### (c) & (d) Confirm non-nulls and check duplicates

In [ ]:
# Data Completeness
shop_summary = pd.DataFrame({
    'Total Rows': len(df_shop_filtered),
    'Values Present': df_shop_filtered.count(),
    'Missing Values': df_shop_filtered.isnull().sum()
})
display(shop_summary)

# Duplicates
print("\nChecking for duplicates:")
dupes = df_shop_filtered[df_shop_filtered.duplicated(keep=False)]
if not dupes.empty:
    display(dupes)
else:
    print("No exact row duplicates found. Displaying head instead:")
    display(df_shop_filtered.head())

                Total Rows  Values Present  Missing Values
Payment_ID              50              50               0
Order_ID                50              50               0
Amount                  50              50               0
Payment_Method          50              50               0
Payment_Status          50              50               0

Checking for duplicates:
No exact row duplicates found. Displaying head instead:

   Payment_ID  Order_ID  Amount    Payment_Method Payment_Status
0           1         1     799               UPI           Paid
1           2         2    2598       Credit Card           Paid
2           3         3     999        Debit Card        Pending
3           4         4    1047  Cash on Delivery           Paid
4           5         5    2998               UPI           Paid